// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SRT.Core.Database.Postgresql.ErrorLog;

#nullable disable

namespace SRT.Core.Database.Postgresql.ErrorLog.Migrations
{
    [DbContext(typeof(ErrorReportDBContext))]
    [Migration("20261004104844_InitialErrorReport")]
    partial class InitialErrorReport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SRT.Core.Database.Postgresql.ErrorLog.Domain.ErrorReport", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DetailJson")
                        .HasColumnType("text");

                    b.Property<string>("Environment")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("ErrorId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExceptionType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Message1")
                        .HasColumnType("text");

                    b.Property<string>("Message2")
                        .HasColumnType("text");

                    b.Property<string>("Message3")
                        .HasColumnType("text");

                    b.Property<string>("Message4")
                        .HasColumnType("text");

                    b.Property<string>("Message5")
                        .HasColumnType("text");

                    b.Property<string>("Operation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Outcome")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Service")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Severity")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StackTrace1")
                        .HasColumnType("text");

                    b.Property<string>("StackTrace2")
                        .HasColumnType("text");

                    b.Property<string>("StackTrace3")
                        .HasColumnType("text");

                    b.Property<string>("StackTrace4")
                        .HasColumnType("text");

                    b.Property<string>("StackTrace5")
                        .HasColumnType("text");

                    b.Property<string>("Target")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Version")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("category")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("layer1")
                        .HasColumnType("text");

                    b.Property<string>("layer10")
                        .HasColumnType("text");

                    b.Property<string>("layer11")
                        .HasColumnType("text");

                    b.Property<string>("layer12")
                        .HasColumnType("text");

                    b.Property<string>("layer13")
                        .HasColumnType("text");

                    b.Property<string>("layer14")
                        .HasColumnType("text");

                    b.Property<string>("layer15")
                        .HasColumnType("text");

                    b.Property<string>("layer16")
                        .HasColumnType("text");

                    b.Property<string>("layer17")
                        .HasColumnType("text");

                    b.Property<string>("layer18")
                        .HasColumnType("text");

                    b.Property<string>("layer19")
                        .HasColumnType("text");

                    b.Property<string>("layer2")
                        .HasColumnType("text");

                    b.Property<string>("layer20")
                        .HasColumnType("text");

                    b.Property<string>("layer3")
                        .HasColumnType("text");

                    b.Property<string>("layer4")
                        .HasColumnType("text");

                    b.Property<string>("layer5")
                        .HasColumnType("text");

                    b.Property<string>("layer6")
                        .HasColumnType("text");

                    b.Property<string>("layer7")
                        .HasColumnType("text");

                    b.Property<string>("layer8")
                        .HasColumnType("text");

                    b.Property<string>("layer9")
                        .HasColumnType("text");

                    b.Property<int>("serviceID")
                        .HasColumnType("integer");

                    b.Property<string>("serviceName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_ErrorReports_CorrelationId");

                    b.HasIndex("ErrorId")
                        .IsUnique()
                        .HasDatabaseName("IX_ErrorReports_ErrorId")
                        .HasFilter("\"ErrorId\" IS NOT NULL");

                    b.HasIndex("Target")
                        .HasDatabaseName("IX_ErrorReports_Target");

                    b.HasIndex("category")
                        .HasDatabaseName("IX_ErrorReports_category");

                    b.HasIndex("serviceID")
                        .HasDatabaseName("IX_ErrorReports_serviceID");

                    b.HasIndex("serviceName")
                        .HasDatabaseName("IX_ErrorReports_serviceName");

                    b.HasIndex("Category", "date")
                        .HasDatabaseName("IX_ErrorReports_Category_date");

                    b.ToTable("ErrorReports", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
