// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SRT.Core.Database.Postgresql.Cache;

#nullable disable

namespace SRT.Core.Database.Postgresql.Cache.Migrations
{
    [DbContext(typeof(CacheDBContext))]
    [Migration("20261004104840_InitialCashBackup")]
    partial class InitialCashBackup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SRT.Core.Database.Postgresql.Cache.Domains.CashBackup", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("category")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("dateCreate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("dateExpire")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("key")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<int>("serviceID")
                        .HasColumnType("integer");

                    b.Property<string>("serviceName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("value1")
                        .HasMaxLength(3990)
                        .HasColumnType("character varying(3990)");

                    b.Property<string>("value2")
                        .HasMaxLength(3990)
                        .HasColumnType("character varying(3990)");

                    b.Property<string>("value3")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("key")
                        .HasDatabaseName("IX_CashBackup_key");

                    b.HasIndex("serviceID")
                        .HasDatabaseName("IX_CashBackup_serviceID");

                    b.HasIndex("serviceName")
                        .HasDatabaseName("IX_CashBackup_serviceName");

                    b.HasIndex("serviceID", "category", "key")
                        .IsUnique()
                        .HasDatabaseName("UX_CashBackup_serviceID_category_key")
                        .HasFilter("\"category\" IS NOT NULL AND \"key\" IS NOT NULL");

                    b.ToTable("CashBackup");
                });
#pragma warning restore 612, 618
        }
    }
}
